### ISSUE TITLE
It doesn't work on beta 6.

### ISSUE THREAD

**Issue by BiggerHao** [flagrow/flarum-ext-image-upload#57]
Oops! Something went wrong. Please reload the page and try again.

The error message is below.

```
500 Internal Server Error

POST https://buaabbs.top/api/image/upload

{
  "errors": [
    {
      "code": 500,
      "title": "Internal server error",
      "detail": "League\\Flysystem\\FileNotFoundException: File not found at path: 1-QRiNVbcTB5ZueFVp.jpeg in /home/hao/buaabbs/vendor/league/flysystem/src/Filesystem.php:385\nStack trace:\n#0 /home/hao/buaabbs/vendor/league/flysystem/src/Filesystem.php(350): League\\Flysystem\\Filesystem->assertPresent('1-QRiNVbcTB5Zue...')\n#1 /home/hao/buaabbs/vendor/flagrow/flarum-ext-image-upload/src/Adapters/LocalAdapter.php(53): League\\Flysystem\\Filesystem->getMetadata('1-QRiNVbcTB5Zue...')\n#2 /home/hao/buaabbs/vendor/flagrow/flarum-ext-image-upload/src/Commands/UploadImageHandler.php(153): Flagrow\\ImageUpload\\Adapters\\LocalAdapter->uploadContents('1-QRiNVbcTB5Zue...', '\\xFF\\xD8\\xFF\\xE0\\x00\\x10JFIF\\x00\\x01\\x01\\x00\\x00...')\n#3 [internal function]: Flagrow\\ImageUpload\\Commands\\UploadImageHandler->handle(Object(Flagrow\\ImageUpload\\Commands\\UploadImage))\n#4 /home/hao/buaabbs/vendor/illuminate/bus/Dispatcher.php(202): call_user_func(Array, Object(Flagrow\\ImageUpload\\Commands\\UploadImage))\n#5 [internal function]: Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Flagrow\\ImageUpload\\Commands\\UploadImage))\n#6 /home/hao/buaabbs/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Flagrow\\ImageUpload\\Commands\\UploadImage))\n#7 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Flagrow\\ImageUpload\\Commands\\UploadImage))\n#8 /home/hao/buaabbs/vendor/illuminate/pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Flagrow\\ImageUpload\\Commands\\UploadImage))\n#9 /home/hao/buaabbs/vendor/illuminate/bus/Dispatcher.php(204): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#10 /home/hao/buaabbs/vendor/illuminate/bus/Dispatcher.php(177): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Flagrow\\ImageUpload\\Commands\\UploadImage), NULL)\n#11 /home/hao/buaabbs/vendor/flagrow/flarum-ext-image-upload/src/Api/Controllers/UploadImageController.php(59): Illuminate\\Bus\\Dispatcher->dispatch(Object(Flagrow\\ImageUpload\\Commands\\UploadImage))\n#12 /home/hao/buaabbs/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(96): Flagrow\\ImageUpload\\Api\\Controllers\\UploadImageController->data(Object(Zend\\Stratigility\\Http\\Request), Object(Tobscure\\JsonApi\\Document))\n#13 /home/hao/buaabbs/vendor/flarum/core/src/Http/Handler/ControllerRouteHandler.php(52): Flarum\\Api\\Controller\\AbstractSerializeController->handle(Object(Zend\\Stratigility\\Http\\Request))\n#14 /home/hao/buaabbs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(71): Flarum\\Http\\Handler\\ControllerRouteHandler->__invoke(Object(Zend\\Stratigility\\Http\\Request), Array)\n#15 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Dispatch.php(82): Flarum\\Http\\Middleware\\DispatchRoute->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#16 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#17 /home/hao/buaabbs/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#18 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Dispatch.php(82): Flarum\\Http\\Middleware\\SetLocale->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#19 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#20 /home/hao/buaabbs/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(57): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#21 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Dispatch.php(82): Flarum\\Http\\Middleware\\AuthenticateWithHeader->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#22 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#23 /home/hao/buaabbs/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(33): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#24 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Dispatch.php(82): Flarum\\Http\\Middleware\\AuthenticateWithSession->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#25 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#26 /home/hao/buaabbs/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(38): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#27 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Dispatch.php(82): Flarum\\Http\\Middleware\\RememberFromCookie->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#28 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#29 /home/hao/buaabbs/vendor/flarum/core/src/Http/Middleware/StartSession.php(33): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#30 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Dispatch.php(82): Flarum\\Http\\Middleware\\StartSession->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#31 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#32 /home/hao/buaabbs/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(32): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#33 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Dispatch.php(82): Flarum\\Api\\Middleware\\FakeHttpMethods->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#34 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#35 /home/hao/buaabbs/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(30): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#36 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Dispatch.php(82): Flarum\\Http\\Middleware\\ParseJsonBody->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#37 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#38 /home/hao/buaabbs/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(75): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#39 /home/hao/buaabbs/vendor/flarum/core/src/Http/AbstractServer.php(53): Zend\\Stratigility\\MiddlewarePipe->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#40 /home/hao/buaabbs/vendor/zendframework/zend-diactoros/src/Server.php(166): Flarum\\Http\\AbstractServer->__invoke(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Diactoros\\Response), NULL)\n#41 /home/hao/buaabbs/vendor/flarum/core/src/Http/AbstractServer.php(34): Zend\\Diactoros\\Server->listen()\n#42 /home/hao/buaabbs/api.php(16): Flarum\\Http\\AbstractServer->listen()\n#43 {main}"
    }
  ]
}
```

**Comment by Luceos** [comment]
What did you do to cause this, because it seems the file could not be found?

**Comment by BiggerHao** [comment]
I just enable the image-upload extension and then try to upload an image in a post. But the error always happens.
I have used this extension in beta 5 and it worked well then. I use the version 0.3.0 of the extension now.

**Comment by Luceos** [comment]
Did your file permissions change? Can you verify the file mentioned in the error is available in your storage directory?

**Comment by BiggerHao** [comment]
The file doesn't exist.
I changed the permission of the images folder and the extension works now.
`sudo chown -R www-data:www-data images/`
Thank you!
